export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  FINANCE = "FINANCE",
  MODERATOR = "MODERATOR",
  SUPPORT = "SUPPORT",
  CONTENT_EDITOR = "CONTENT_EDITOR",
  VERIFIED_ARTIST = "VERIFIED_ARTIST",
  INDEPENDENT_ARTIST = "INDEPENDENT_ARTIST",
  LABEL = "LABEL",
  MANAGER = "MANAGER",
  PREMIUM_LISTENER = "PREMIUM_LISTENER",
  FREE_LISTENER = "FREE_LISTENER",
  LISTENER = "LISTENER",
  ARTIST = "ARTIST",
}

export const ADMIN_ROLES: Role[] = [Role.SUPER_ADMIN, Role.ADMIN, Role.FINANCE, Role.MODERATOR, Role.SUPPORT, Role.CONTENT_EDITOR];
export const ARTIST_ROLES: Role[] = [Role.VERIFIED_ARTIST, Role.INDEPENDENT_ARTIST, Role.LABEL, Role.MANAGER, Role.ARTIST];
export const LISTENER_ROLES: Role[] = [Role.PREMIUM_LISTENER, Role.FREE_LISTENER, Role.LISTENER];
